<?php
use Acelaya\Website\Form\ContactFilter;
?>

<?php $this->layout('Acelaya::layout') ?>

<?php $this->start('main') ?>
    <section id="fh5co-hero" class="no-js-fullheight" style="background-image: url(/img/hero_bg.jpg);" data-next="yes">
        <div class="fh5co-overlay"></div>
        <div class="container">
            <div class="fh5co-intro no-js-fullheight">
                <div class="fh5co-intro-text">
                    <div class="fh5co-center-position">
                        <h2 class="animate-box"><?= $this->translate('Contact') ?></h2>
                        <h3 class="animate-box">
                            <?= $this->translate('If you need to contact me for any reason, feel free to do it.') ?>
                            <br>
                            <?= $this->translate('I\'ll get back to you as soon as possible.') ?>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="fh5co-learn-more animate-box">
            <a href="#" class="scroll-btn">
                <span class="arrow"><i class="icon-chevron-down"></i></span>
            </a>
        </div>
    </section>

    <section id="fh5co-features">
        <div class="container animate-box">
            <?php if (isset($errors)): ?>
                <div class="alert alert-danger fade in">
                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                    <span class="fa fa-times"></span>
                    <?php if (empty($errors)): ?>
                        <?= $this->translate('Something went wrong while sending the email. Try again later.') ?>
                    <?php else: ?>
                        <?= $this->translate('Information provided is not valid. Review form data and send it again.') ?>
                    <?php endif; ?>
                </div>
            <?php elseif (isset($success)): ?>
                <div class="alert alert-success fade in">
                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                    <span class="fa fa-check"></span><?= $this->translate('Contact properly sent. Thanks!') ?>
                </div>
            <?php endif; ?>

            <?php $currentData = $currentData ?? []; ?>
            <form  action="<?= $this->assemble_url('contact', true) ?>" name="contactForm" id="contactForm" method="post">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group <?= isset($errors[ContactFilter::NAME]) ? 'has-error' : '' ?>">
                            <input type="text" name="<?= ContactFilter::NAME ?>"
                                   placeholder="<?= $this->translate('Name') ?>" class="form-control" id="name"
                                   value="<?= $currentData[ContactFilter::NAME] ?>">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group <?= isset($errors[ContactFilter::EMAIL]) ? 'has-error' : '' ?>">
                            <input type="email" name="<?= ContactFilter::EMAIL ?>"
                                   placeholder="<?= $this->translate('Email') ?>" class="form-control" id="email"
                                   value="<?= $currentData[ContactFilter::EMAIL] ?>">
                        </div>
                    </div>
                </div>
                <div class="form-group <?= isset($errors[ContactFilter::SUBJECT]) ? 'has-error' : '' ?>">
                    <input type="text" name="<?= ContactFilter::SUBJECT ?>"
                           placeholder="<?= $this->translate('Subject') ?>" class="form-control" id="subject"
                           value="<?= $currentData[ContactFilter::SUBJECT] ?>">
                </div>
                <div class="form-group <?= isset($errors[ContactFilter::COMMENTS]) ? 'has-error' : '' ?>">
                <textarea name="<?= ContactFilter::COMMENTS ?>" rows="10"
                          placeholder="<?= $this->translate('Message') ?>" class="form-control" id="comments"
                ><?= $currentData[ContactFilter::COMMENTS] ?></textarea>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <?= $this->recaptcha_input($this->locale()) ?>
                    </div>
                    <div class="col-lg-8 col-md-6 col-sm-6 text-right">
                        <div class="form-group ">
                            <button type="submit" name="submit" class="btn btn-primary" disabled
                                    data-loading-text="<?= $this->translate('Sending...') ?>">
                                <?= $this->translate('Submit') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
<?php $this->end() ?>
