<?php $this->layout('Acelaya::layout') ?>

<?php $this->start('main') ?>
    <section id="fh5co-hero" class="js-fullheight" style="background-image: url(/img/hero_bg.jpg);" data-next="yes">
        <div class="fh5co-overlay"></div>
        <div class="container">
            <div class="fh5co-intro js-fullheight">
                <div class="fh5co-intro-text">
                    <div class="fh5co-center-position">
                        <div class="animate-box">
                            <img src="/img/me.jpg" class="me">
                            <h2>Alejandro Celaya<br>Full-stack developer</h2>
                            {{ render_social_menu() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="fh5co-learn-more animate-box">
            <a href="#" class="scroll-btn">
                <span class="arrow"><i class="icon-chevron-down"></i></span>
            </a>
        </div>
    </section>

    <section id="fh5co-testimonials">
        <div class="container">
            <div class="row row-bottom-padded-sm">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <h2 class="fh5co-lead animate-box"><?= $this->translate('Hello!<br>My name is Alejandro Celaya.') ?></h2>
                </div>
            </div>
            <div class="animate-box">
                <ul class="slides text-justify">
                    <li>
                        <blockquote>
                            <p><?= $this->translate('I live in Zaragoza, Spain, and I am a web developer since 2010.') ?></p>
                            <p><?= $this->translate('I have worked in many kind of projects. From simple static webpages to fully managed web applications, web services or eCommerce applications.') ?></p>
                            <p>
                                <?= sprintf(
                                    $this->translate('I am focused on %1$sPHP%2$s and %1$sJavascript%2$s, but I\'ve also worked with other technologies, like %1$sJava%2$s and %1$sAndroid%2$s.'),
                                    '<b>',
                                    '</b>'
                                ) ?>
                            </p>
                            <p>
                                <?= sprintf(
                                    $this->translate('I love open source software, and I contribute with it whenever I can, providing new features, bug fixes or improving documentation. I\'ve created my own OSS projects too, that can be found in my %sGithub%s account.'),
                                    '<a target="_blank" href="https://github.com/acelaya">',
                                    '</a>'
                                ) ?>
                            </p>
                            <p><?= $this->translate('I\'m a passionate programmer. I love my job and always give my best. I\'m very committed with what I do, and always try to learn new things and be active.') ?></p>
                            <p>
                                <?= sprintf(
                                    $this->translate('In January 2013 I was included in the %1$sZend Certified Engineers%2$s group by passing the official certification exam (PHP 5.3). In May 2014 I passed the %1$sZend Framework 2 Certified Architect%2$s exam too.'),
                                    '<a target="_blank" href="https://www.zend.com/en/yellow-pages/ZEND021590">',
                                    '</a>'
                                ) ?>
                            </p>

                        </blockquote>
                    </li>
                </ul>
            </div>
        </div>
    </section>
<?php $this->stop() ?>
