<?php $this->layout('Acelaya::layout') ?>

<?php $this->start('main') ?>
    <section id="fh5co-hero" class="no-js-fullheight" style="background-image: url(/img/hero_bg.jpg);" data-next="yes">
        <div class="fh5co-overlay"></div>
        <div class="container">
            <div class="fh5co-intro no-js-fullheight">
                <div class="fh5co-intro-text">
                    <div class="fh5co-center-position">
                        <h2 class="animate-box"><?= $this->translate('Projects') ?></h2>
                        <h3 class="animate-box">
                            <?= $this->translate('In the last years I have worked in many projects.') ?>
                            <br>
                            <?= $this->translate('This is just a small sample of the projects that I still maintain.') ?>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="fh5co-learn-more animate-box">
            <a href="#" class="scroll-btn">
                <span class="arrow"><i class="icon-chevron-down"></i></span>
            </a>
        </div>
    </section>

    <section id="fh5co-projects">
        <div class="container">
            <div class="row row-bottom-padded-md">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <h2 class="fh5co-lead animate-box"><?= $this->translate('My projects') ?></h2>
                    <p class="fh5co-sub-lead animate-box"><?= $this->translate('') ?></p>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <a href="https://shlink.io" class="fh5co-project-item" target="_blank">
                        <div style="background: #4696e5">
                            <img src="/img/projects/shlink-logo.png" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate('Shlink') ?></h2>
                            <p><?= sprintf(
                                $this->translate('Shlink is a self-hosted URL shortener built with PHP, using %1$sZend Expressive%2$s as the base framework and then using %1$scomposer%2$s to add other useful tools like %1$sDoctrine ORM%2$s, %1$sSymfony console%2$s or %1$sTwig%2$s.'),
                                '<b>',
                                '</b>'
                            ) ?></p>
                        </div>
                    </a>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <div class="fh5co-project-item">
                        <div style="background: #3e9cfe">
                            <img src="/img/projects/subclient.png" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate("Subclient") ?></h2>
                            <p><?= sprintf(
                                $this->translate('Subclient is a cross-platform audio and video streaming application that works as a %1$sSubsonic%2$s client. it is Created with Java Swing and makes use of %1$sSubconnector%2$s to connect with servers.'),
                                '<b>',
                                '</b>'
                            ) ?></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <div class="fh5co-project-item">
                        <div style="background: #68b604">
                            <img src="/img/projects/zf2-logo.png" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate('Zend Framework modules') ?></h2>
                            <p><?= sprintf(
                                $this->translate('I have published some ZF modules that can be installed with %scomposer%s. These are the most remarkable:'),
                                '<a href="https://getcomposer.org/" target="_blank">',
                                '</a>'
                            ) ?></p>
                            <ul class="zf-modules-list">
                                <li>
                                    <i class="icon-check2"></i>
                                    <a href="https://github.com/acelaya/ZF2-AcMailer" target="_blank">ZF2-AcMailer</a>:
                                    <?= $this->translate('a fully-featured module to send emails.') ?>
                                </li>
                                <li>
                                    <i class="icon-check2"></i>
                                    <a href="https://github.com/acelaya/ZF2-AcQrCode" target="_blank">ZF2-AcQrCode</a>:
                                    <?= sprintf(
                                        $this->translate('a module to generate QR codes based on the %sEndroid QR code%s library.'),
                                        '<a href="https://github.com/endroid/QrCode" target="_blank">',
                                        '</a>'
                                    ) ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <a href="https://blog.alejandrocelaya.com" class="fh5co-project-item" target="_blank">
                        <div style="background: #050505">
                            <img src="/img/projects/spress-logo.png" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate('Spress blog') ?></h2>
                            <p><?= sprintf(
                                $this->translate('Some time ago I started to write a blog. In the past my blogging platform was Wordpress, but I didn\'t feel comfortable with it, so I changed to Sculpin, and later, to %1$sSpress%2$s. Both are static site generaters based on %1$sSymfony%2$s components with which I\'ve created a blazing fast and SEO-friendly blog.'),
                                '<b>',
                                '</b>'
                            ) ?></p>
                        </div>
                    </a>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <div class="fh5co-project-item">
                        <div style="background: #70b3ce">
                            <img src="/img/projects/webs.jpg" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate('Websites') ?></h2>
                            <p><?= sprintf(
                                $this->translate('I tend to use %1$sZend Expressive%2$s for all the websites I create. It is a microframework that allows fast development and prototyping, but scales so well that it is never too small.'),
                                '<a target="_blanck" href="https://docs.zendframework.com/zend-expressive/">',
                                '</a>'
                            ) ?></p>
                            <p><?= sprintf(
                                $this->translate('For the front-end I use tools like %sbootstrap%s with %ssass%s, and always applaying the latest web standards, like %sHTML5%s.'),
                                '<a target="_blank" href="http://getbootstrap.com/">',
                                '</a>',
                                '<a target="_blank" href="http://sass-lang.com/">',
                                '</a>',
                                '<b>',
                                '</b>'
                            ) ?></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12 animate-box">
                    <a href="https://github.com/acelaya" class="fh5co-project-item" target="_blank">
                        <div style="background: #4183c4">
                            <img src="/img/projects/github.png" class="img-responsive">
                        </div>
                        <div class="fh5co-text">
                            <h2><?= $this->translate('Other projects') ?></h2>
                            <p><?= $this->translate('I have worked in other minor projects too. Tiny CSS libraries, other Zend Framework modules and such.') ?></p>
                            <p><?= sprintf($this->translate('All of them can be found on my %sGithub%s profile.'), '<b>', '</b>') ?></p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </section>
<?php $this->stop() ?>
